# Generated by Django 6.0.3 on 2026-03-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ideal_soil", models.CharField(max_length=100)),
                ("ideal_season", models.CharField(max_length=50)),
                ("water_requirement", models.CharField(max_length=50)),
                (
                    "yield_estimate",
                    models.FloatField(help_text="Expected yield in tons per acre"),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("instruction", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crops.crop"
                    ),
                ),
            ],
        ),
    ]
