# Generated by Django 6.0.3 on 2026-03-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        ("land", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="land",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="land.land"
            ),
        ),
    ]
